"""
# English

class - Template to create new objects
- Class will generate new objects (instances) that could have your own attributes and methods.
- instances generated by Class could use your own intern attribute to realize many actions.
- By convetion we use PascalCase to name classes.

# Portuguese

class - Um template para criar novos objetos
- Classes vao gerar novos objetos (instancias) que podem ter seus proprios atributos e metodos.
- instancias geradas pela classe podem usar seus atributos internos para realizar varias acoes
- Por convencao nos usamos PascalCase para nomear classes.
"""

# Creating class Person
class Person:
    ...


# To create an instance of class Person, we will use as Person()
person1 = Person()

# To use Person attributes, we will access using dot and the attribute name.
# For example, .name
person1.name = 'John'
person1.last_name = 'Doe'
print(person1.name)
print(person1.last_name)

# If we want to create a new instance, we have to do the same but put in another variable
person2 = Person()
person2.name = 'Patricia'
person2.last_name = 'Waters'
print(person2.name)
print(person2.last_name)
