from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

# Sizing
BIGGEST_FONT_SIZE = 20
MEDIUM_FONT_SIZE = 16
SMALLEST_FONT_SIZE = 12
MINIMUM_WIDTH = 350

# Margin
TEXT_MARGIN = 8

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
